---
abstract: 'a smokebrew plugin to configure things like BINGOS does'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SmokeBrew-Plugin-BINGOS
requires:
  App::SmokeBrew: 0.28
  Moose: 1.03
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/app-smokebrew-plugin-bingos
  repository: https://github.com/bingos/app-smokebrew-plugin-bingos.git
version: 0.08
